// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFLEDVHLiK6BPJa22qHtct7bJNkfE0BIM',
    appId: '1:5286856852:web:38f7c18d3acc066eb1cc81',
    messagingSenderId: '5286856852',
    projectId: 'coffee-apk',
    authDomain: 'coffee-apk.firebaseapp.com',
    storageBucket: 'coffee-apk.firebasestorage.app',
    measurementId: 'G-NBHBCCZ20Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN5CItZdp_sjpGPpRe4aDrYzTf9OvvOTQ',
    appId: '1:5286856852:android:73c06ecd453922feb1cc81',
    messagingSenderId: '5286856852',
    projectId: 'coffee-apk',
    storageBucket: 'coffee-apk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC77eoJ1DgF9l7TiFMXs2XH1VvHb_tTCA8',
    appId: '1:5286856852:ios:e7e963b8aa9e2d90b1cc81',
    messagingSenderId: '5286856852',
    projectId: 'coffee-apk',
    storageBucket: 'coffee-apk.firebasestorage.app',
    iosBundleId: 'com.example.roastoryMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC77eoJ1DgF9l7TiFMXs2XH1VvHb_tTCA8',
    appId: '1:5286856852:ios:e7e963b8aa9e2d90b1cc81',
    messagingSenderId: '5286856852',
    projectId: 'coffee-apk',
    storageBucket: 'coffee-apk.firebasestorage.app',
    iosBundleId: 'com.example.roastoryMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFLEDVHLiK6BPJa22qHtct7bJNkfE0BIM',
    appId: '1:5286856852:web:3697a370a8a11d18b1cc81',
    messagingSenderId: '5286856852',
    projectId: 'coffee-apk',
    authDomain: 'coffee-apk.firebaseapp.com',
    storageBucket: 'coffee-apk.firebasestorage.app',
    measurementId: 'G-4KQEH6LXPZ',
  );
}
